version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "JSONbored"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    # Group dependency updates
    groups:
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier*"
          - "jest*"
          - "typescript"
      build-dependencies:
        patterns:
          - "vite*"
          - "rollup*"
          - "webpack*"
          - "babel*"
    # Auto-merge minor updates for dev dependencies
    allow:
      - dependency-type: "development"
        update-type: "version-update:semver-patch"
      - dependency-type: "development"
        update-type: "version-update:semver-minor"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "JSONbored"
    commit-message:
      prefix: "ci"
      include: "scope"