name: Bug Report
description: File a bug report to help us improve Zodded
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: input
    id: version
    attributes:
      label: Zodded Version
      description: What version of Zodded are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you running?
      options:
        - "16.x"
        - "18.x"
        - "20.x"
        - "Other (please specify in description)"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - "Windows"
        - "macOS"
        - "Linux"
        - "Other (please specify in description)"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "When I run zodkit analyze, it crashes with..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run `zodkit analyze`
        2. With configuration file: ...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: "The command should complete successfully and show validation results"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: "The command crashed with the following error..."
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Your Zodded configuration file (if applicable)
      render: javascript
      placeholder: |
        module.exports = {
          schemas: {
            patterns: ['./src/**/*.ts']
          }
        };

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Any relevant log output or error messages
      render: shell
      placeholder: "Paste error logs here..."

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: "This issue started after upgrading from version..."

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have included all relevant information above
          required: true
        - label: I can reproduce this issue consistently
          required: true