name: Feature Request
description: Suggest an idea for Zodded
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide detailed information about your request.

  - type: input
    id: title
    attributes:
      label: Feature Title
      description: A clear and concise title for the feature
      placeholder: "Add support for custom validation rules"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: "I would like Zodded to support..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: "Alternatively, we could..."

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Low - Nice to have"
        - "Medium - Would be helpful"
        - "High - Blocking my workflow"
        - "Critical - Urgent need"
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - "Low - Simple addition"
        - "Medium - Moderate changes required"
        - "High - Significant implementation effort"
        - "Unknown"

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature
      placeholder: "In my project, I need to..."
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide code examples or mockups if applicable
      render: typescript
      placeholder: |
        // Example usage
        zodkit analyze --custom-rules ./my-rules.js

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or links about the feature request here
      placeholder: "This feature would complement..."

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided a clear description of the feature
          required: true
        - label: I have explained the use case and benefits
          required: true